// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByfz1UfE56eNTqwEQx4NjJFt07X88KjLw',
    appId: '1:485865464939:web:1fdc20e8a7f88a277c7d2e',
    messagingSenderId: '485865464939',
    projectId: 'yelloskye-bf39c',
    authDomain: 'yelloskye-bf39c.firebaseapp.com',
    storageBucket: 'yelloskye-bf39c.firebasestorage.app',
    measurementId: 'G-3MVKW4ZWR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHkdf-eOJz6X-ovn4tVUbvd951PF5JVcI',
    appId: '1:485865464939:android:b8aa954ad41e9d037c7d2e',
    messagingSenderId: '485865464939',
    projectId: 'yelloskye-bf39c',
    storageBucket: 'yelloskye-bf39c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLm50XoEshh3m0oY34C3gSANG6XksxrGg',
    appId: '1:485865464939:ios:7605c7a03fe785e47c7d2e',
    messagingSenderId: '485865464939',
    projectId: 'yelloskye-bf39c',
    storageBucket: 'yelloskye-bf39c.firebasestorage.app',
    iosBundleId: 'com.example.yelloskye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLm50XoEshh3m0oY34C3gSANG6XksxrGg',
    appId: '1:485865464939:ios:7605c7a03fe785e47c7d2e',
    messagingSenderId: '485865464939',
    projectId: 'yelloskye-bf39c',
    storageBucket: 'yelloskye-bf39c.firebasestorage.app',
    iosBundleId: 'com.example.yelloskye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByfz1UfE56eNTqwEQx4NjJFt07X88KjLw',
    appId: '1:485865464939:web:2eba9a193f01337a7c7d2e',
    messagingSenderId: '485865464939',
    projectId: 'yelloskye-bf39c',
    authDomain: 'yelloskye-bf39c.firebaseapp.com',
    storageBucket: 'yelloskye-bf39c.firebasestorage.app',
    measurementId: 'G-3KKN8MBR9H',
  );
}
